OKTW-Network/Galaxy

src/main/kotlin/one/oktw/galaxy/command/TeleportAsk.kt, src/main/kotlin/one/oktw/galaxy/command/TeleportHereAsk.kt, src/main/kotlin/one/oktw/galaxy/internal/CommandRegister.kt
=> Rename teleport command class file 

src/main/kotlin/one/oktw/galaxy/command/Hat.kt, src/main/kotlin/one/oktw/galaxy/internal/CommandRegister.kt
=> Add hat command

src/main/kotlin/one/oktw/galaxy/CommandRegister.kt, src/main/kotlin/one/oktw/galaxy/command/Sign.kt
=> Add sign command

src/main/kotlin/one/oktw/galaxy/Main.kt
=> noun -> v-ing

src/main/kotlin/one/oktw/galaxy/manager/GalaxyManager.kt
解決 https://github.com/OKTW-Network/Galaxy/pull/30#issuecomment-374080505
=> Cache galaxy

src/main/kotlin/one/oktw/galaxy/gui/GUI.kt
=> Clean up GUI event process

src/main/kotlin/one/oktw/galaxy/event/Armor.kt, src/main/kotlin/one/oktw/galaxy/event/DisableDrop.kt, src/main/kotlin/one/oktw/galaxy/event/ItemProtect.kt, src/main/kotlin/one/oktw/galaxy/register/EventRegister.kt
=> Disable plugin item move out from player inventory

build.gradle, src/main/kotlin/one/oktw/galaxy/gui/PageGUI.kt, src/main/kotlin/one/oktw/galaxy/types/item/Button.kt
update kotlin to 1.2.31
import enum
=> Update kotlin and clean up

src/main/kotlin/one/oktw/galaxy/internal/DatabaseManager.kt
fix #42 break database default config save
=> Fix Database default config not save

src/main/kotlin/one/oktw/galaxy/armor/ArmorEffect.kt, src/main/kotlin/one/oktw/galaxy/item/service/CoolDown.kt, src/main/kotlin/one/oktw/galaxy/machine/chunkloader/ChunkLoaderManager.kt, src/main/kotlin/one/oktw/galaxy/traveler/service/ActionBar.kt
using iterator to safety remove entities from array/map
=> Fix actionbar throw exception on relogin

src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt, src/main/kotlin/one/oktw/galaxy/gui/GUIHelper.kt
=> Fix join planet GUI close event not handle

src/main/kotlin/one/oktw/galaxy/galaxy/data/Galaxy.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt, src/main/kotlin/one/oktw/galaxy/gui/GalaxyInfo.kt, src/main/kotlin/one/oktw/galaxy/gui/GalaxyManagement.kt
=> Add galaxy info and notice

src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt
=> Member status

src/main/kotlin/one/oktw/galaxy/galaxy/GalaxyManager.kt
fix get planet and safety save galaxy
=> Fix get planet

src/main/kotlin/one/oktw/galaxy/Main.kt, src/main/kotlin/one/oktw/galaxy/galaxy/planet/PlanetHelper.kt, src/main/kotlin/one/oktw/galaxy/galaxy/planet/gen/PlanetGenModifier.kt, src/main/kotlin/one/oktw/galaxy/galaxy/planet/gen/populator/Spawn.kt
生成自定義世界重生點
修正重生點位置
修正世界邊界中心
~~先合併 #56~~
=> Spawn generator

src/main/kotlin/one/oktw/galaxy/Main.kt, src/main/kotlin/one/oktw/galaxy/galaxy/planet/TeleportHelper.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt, src/main/kotlin/one/oktw/galaxy/gui/GUIHelper.kt, src/main/kotlin/one/oktw/galaxy/gui/machine/ChunkLoader.kt, src/main/kotlin/one/oktw/galaxy/item/event/Gun.kt, src/main/kotlin/one/oktw/galaxy/machine/chunkloader/ChunkLoader.kt, src/main/kotlin/one/oktw/galaxy/machine/chunkloader/ChunkLoaderManager.kt, src/main/kotlin/one/oktw/galaxy/traveler/event/Viewer.kt
=> Clean up async functional

src/main/kotlin/one/oktw/galaxy/block/event/FakeBlock.kt, src/main/kotlin/one/oktw/galaxy/galaxy/planet/event/SpawnProtect.kt, src/main/kotlin/one/oktw/galaxy/internal/register/EventRegister.kt
=> Spawn protect

src/main/kotlin/one/oktw/galaxy/galaxy/GalaxyManager.kt, src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
=> Try fix player inventory loss

src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
=> fix again player data save

src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
如果在載入之前撿起物品會造成物品消失
在載入前將玩家設定為訪客模式避免與世界互動
=> Fix load player data cause item loss

src/main/kotlin/one/oktw/galaxy/internal/register/EventRegister.kt, src/main/kotlin/one/oktw/galaxy/player/event/Harvest.kt
=> Right click harvest

src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
=> Fix viewer

src/main/kotlin/one/oktw/galaxy/block/event/FakeBlock.kt
=> Skip unbreakable custom block

src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
=> 跳過儲存訪客模式玩家

src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
=> 確保關閉伺服器時儲存所有資料

src/main/kotlin/one/oktw/galaxy/player/event/Viewer.kt
=> Remove viewer after disconnect event

src/main/kotlin/one/oktw/galaxy/block/event/FakeBlock.kt
=> Fix custom block replace exist block

src/main/kotlin/one/oktw/galaxy/block/event/FakeBlock.kt
=> Revert "Fix custom block replace exist block"

src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
* change range to 16 blocks
* fix teleport sound position
=> Change elevator teleport limit to 16 blocks

src/main/kotlin/one/oktw/galaxy/gui/GUIHelper.kt, src/main/kotlin/one/oktw/galaxy/gui/MainMenu.kt
修正MainMenu的按鈕在玩家意外斷線後無法使用
以及玩家斷線後沒有刪除GUI狀態造成Memory leak
=> Fix GUI button and memory leak

src/main/kotlin/one/oktw/galaxy/command/admin/GalaxyInfo.kt, src/main/kotlin/one/oktw/galaxy/command/admin/GalaxyManage.kt, src/main/kotlin/one/oktw/galaxy/command/admin/PlayerInfo.kt
=> Reformat code

build.gradle, src/main/kotlin/one/oktw/galaxy/block/event/BlockGUI.kt, src/main/kotlin/one/oktw/galaxy/command/admin/GalaxyInfo.kt, src/main/kotlin/one/oktw/galaxy/command/admin/GalaxyManage.kt, src/main/kotlin/one/oktw/galaxy/command/admin/Gun.kt, src/main/kotlin/one/oktw/galaxy/command/admin/PlayerInfo.kt, src/main/kotlin/one/oktw/galaxy/economy/event/EconomyEvent.kt, src/main/kotlin/one/oktw/galaxy/economy/service/EconomyService.kt, src/main/kotlin/one/oktw/galaxy/galaxy/GalaxyManager.kt, src/main/kotlin/one/oktw/galaxy/galaxy/data/extensions/Galaxy.kt, src/main/kotlin/one/oktw/galaxy/galaxy/planet/TeleportHelper.kt, src/main/kotlin/one/oktw/galaxy/galaxy/planet/data/extensions/Planet.kt, src/main/kotlin/one/oktw/galaxy/galaxy/planet/gen/populator/Spawn.kt, src/main/kotlin/one/oktw/galaxy/galaxy/traveler/TravelerHelper.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt, src/main/kotlin/one/oktw/galaxy/gui/GalaxyJoinRequest.kt, src/main/kotlin/one/oktw/galaxy/gui/MainMenu.kt, src/main/kotlin/one/oktw/galaxy/gui/PageGUI.kt, src/main/kotlin/one/oktw/galaxy/internal/DatabaseManager.kt, src/main/kotlin/one/oktw/galaxy/internal/register/DataRegister.kt, src/main/kotlin/one/oktw/galaxy/machine/chunkloader/ChunkLoaderManager.kt, src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Switch mongodb driver from mongodb-driver-sync to mongodb-driver-reactivestreams
Rewrite PageGUI
Fix #122
=> Refacetor mongodb async

src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt, src/main/kotlin/one/oktw/galaxy/gui/GalaxyJoinRequest.kt, src/main/kotlin/one/oktw/galaxy/gui/PageGUI.kt, src/main/kotlin/one/oktw/galaxy/item/event/ItemProtect.kt, src/main/kotlin/one/oktw/galaxy/player/event/Viewer.kt
* 平行生成瀏覽介面的物品
* 使用Java API過濾碰撞影響的Entity
* 只讓玩家觸發電梯事件
* 只檢查由玩家觸發的物品掉落事件
=> Performance

src/main/kotlin/one/oktw/galaxy/command/Spawn.kt, src/main/kotlin/one/oktw/galaxy/economy/event/EconomyEvent.kt, src/main/kotlin/one/oktw/galaxy/item/service/CoolDown.kt, src/main/kotlin/one/oktw/galaxy/player/service/ActionBar.kt
修正Actionbar不是執行序安全
同時讓獲得星塵只在數量>0時顯示
=> Fix actionbar thread safe

src/main/kotlin/one/oktw/galaxy/gui/GUIHelper.kt, src/main/kotlin/one/oktw/galaxy/gui/NumberSelect.kt, src/main/kotlin/one/oktw/galaxy/item/enums/ButtonType.kt, src/main/kotlin/one/oktw/galaxy/item/type/Button.kt
=> Number select

src/main/kotlin/one/oktw/galaxy/block/event/FakeBlock.kt, src/main/kotlin/one/oktw/galaxy/event/PlaceCustomBlockEvent.kt, src/main/kotlin/one/oktw/galaxy/event/RemoveCustomBlockEvent.kt
Add two custom event to tell the plugin when custom block is placed or removed
=> Add cumstom event for custom block place/remove

src/main/kotlin/one/oktw/galaxy/machine/chunkloader/data/ChunkLoader.kt
=> Fix ChunkLoader POJO

.editorconfig, .idea/codeStyles/Project.xml
* 增加單行長度限制
* 增加EditorConfig設定檔
=> Max line length & EditorConfig

src/main/kotlin/one/oktw/galaxy/util/Chat.kt, src/main/resources/assets/galaxy/lang/en-US.cfg, src/main/resources/assets/galaxy/lang/zh-TW.cfg
* 增加輸入與確認方法
* 增加單行長度限制
* 增加EditorConfig設定檔
=> Chat input and confirm

src/main/kotlin/one/oktw/galaxy/galaxy/planet/data/Planet.kt, src/main/kotlin/one/oktw/galaxy/galaxy/planet/enums/PlanetType.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt, src/main/kotlin/one/oktw/galaxy/item/enums/ButtonType.kt
=> Planet type

src/main/kotlin/one/oktw/galaxy/command/admin/GalaxyInfo.kt, src/main/kotlin/one/oktw/galaxy/command/admin/GalaxyManage.kt
- Fix admin delete owner
- Rewrite fetch galaxy
=> Admin Commands fix

src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
=> Fix swich planet

src/main/kotlin/one/oktw/galaxy/gui/machine/ChunkLoader.kt, src/main/kotlin/one/oktw/galaxy/machine/chunkloader/ChunkLoader.kt, src/main/kotlin/one/oktw/galaxy/machine/chunkloader/ChunkLoaderManager.kt
=> Fix chunk loader position

src/main/kotlin/one/oktw/galaxy/gui/MainMenu.kt
=> Add text to show GalaxyManagement

src/main/kotlin/one/oktw/galaxy/galaxy/traveler/TravelerHelper.kt, src/main/kotlin/one/oktw/galaxy/galaxy/traveler/data/Traveler.kt
=> Pre galaxy ender chest

.circleci/config.yml, .travis.yml, build.gradle
關閉build cache修正mixin refmap沒有生成的問題
=> Fix mixin refmap gen

src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt, src/main/kotlin/one/oktw/galaxy/gui/GalaxyJoinRequest.kt, src/main/kotlin/one/oktw/galaxy/gui/PageGUI.kt
=> Add page number

build.gradle, src/main/java/one/oktw/galaxy/mixin/MixinCommandBase.java, src/main/java/one/oktw/galaxy/mixin/MixinWorldProviderHell.java, src/main/java/one/oktw/galaxy/mixin/MixinWorldServer.java, src/main/resources/mixins.galaxy.json
* Java 8 的 `UUID.fromString()` 非常慢，所以先檢查長度是否為合法的UUID
* 在世界unload時關閉async lighing thread
* 修正refmap
=> Fix some vanilla performance issue

src/main/kotlin/one/oktw/galaxy/command/admin/GalaxyManage.kt
+Admin send error message to sender
=> Admin create nether

src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt, src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt, src/main/kotlin/one/oktw/galaxy/gui/Confirm.kt, src/main/kotlin/one/oktw/galaxy/gui/CreatePlanet.kt, src/main/kotlin/one/oktw/galaxy/gui/GUI.kt, src/main/kotlin/one/oktw/galaxy/gui/GalaxyInfo.kt, src/main/kotlin/one/oktw/galaxy/gui/GalaxyJoinRequest.kt, src/main/kotlin/one/oktw/galaxy/gui/GalaxyManagement.kt, src/main/kotlin/one/oktw/galaxy/gui/GroupSelect.kt, src/main/kotlin/one/oktw/galaxy/gui/MainMenu.kt, src/main/kotlin/one/oktw/galaxy/gui/ManageMember.kt, src/main/kotlin/one/oktw/galaxy/gui/NumberSelect.kt, src/main/kotlin/one/oktw/galaxy/gui/UpgradeSlot.kt, src/main/kotlin/one/oktw/galaxy/gui/machine/ChunkLoader.kt, src/main/kotlin/one/oktw/galaxy/gui/machine/PlanetTerminal.kt
Unsafe workaround for sponge inventory listener memory leak
revert if sponge fix this issue
=> Memory leak workaround

src/main/kotlin/one/oktw/galaxy/item/event/Gun.kt
listen super event cause sponge process all sub-event for it
=> just listen needed event

src/main/kotlin/one/oktw/galaxy/player/event/Viewer.kt
=> Fix place blocks on block with custom gui in viewer mode when sneaking

src/main/kotlin/one/oktw/galaxy/block/enums/CustomBlocks.kt, src/main/kotlin/one/oktw/galaxy/block/event/BlockGUI.kt, src/main/kotlin/one/oktw/galaxy/block/event/FakeBlock.kt
=> Fix place block when open custom gui

src/main/kotlin/one/oktw/galaxy/player/event/Viewer.kt
=> Fix viewer collide entity

src/main/kotlin/one/oktw/galaxy/gui/CreatePlanet.kt, src/main/resources/assets/galaxy/lang/en-US.cfg, src/main/resources/assets/galaxy/lang/zh-TW.cfg
=> Error message

src/main/kotlin/one/oktw/galaxy/player/event/Viewer.kt
=> fix viewer cause can't pick up item

src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
=> fix player login on deleted world cause world gen

src/main/kotlin/one/oktw/galaxy/block/event/FakeBlock.kt
only check data block type when block is mob spawner
=> Try to fix performance when break block

src/main/kotlin/one/oktw/galaxy/book/BookUtil.kt, src/main/kotlin/one/oktw/galaxy/command/admin/Book.kt, src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Fix when joining lobby book object not updated
=> BookUtil to Companion object

build.gradle
=> clean up build.gradle

build.gradle, src/main/kotlin/one/oktw/galaxy/Main.kt
=> update minecraft mapping to stable_39

.circleci/config.yml
=> Use gradle wrapper

src/main/kotlin/one/oktw/galaxy/gui/machine/Teleporter.kt
=> Try fix #227

src/main/kotlin/one/oktw/galaxy/gui/machine/Teleporter.kt, src/main/kotlin/one/oktw/galaxy/machine/teleporter/TeleporterHelper.kt
=> Fix issue 232

src/main/kotlin/one/oktw/galaxy/internal/register/EasyRecipeRegister.kt
- Fix varible name
- Add more recipe
ToTest:
- slab to block 放橫的
=> More EZ Recipe

build.gradle
Reduce jar size from 5.3 to 5.1
=> Filter metadata files

src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerChat_MeCommand.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerChat_NetworkHandler.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerChat_SayCommand.java, src/main/kotlin/one/oktw/galaxy/event/EventManager.kt, src/main/kotlin/one/oktw/galaxy/event/type/CancelableEvent.kt, src/main/kotlin/one/oktw/galaxy/event/type/PlayerChatEvent.kt, src/main/resources/fabric.mod.json, src/main/resources/galaxy.mixin.json
=> Add a Chat event

.gitlab-ci.yml, .gitmodules
Build plugin and build Docker image then push it to registry.
=> Add GitLab CI

src/main/kotlin/one/oktw/galaxy/Main.kt, src/main/kotlin/one/oktw/galaxy/resourcepack/ResourcePack.kt
=> Get hash from url(ResourcePack)

build.gradle.kts
=> Update to 1.14.4

build.gradle.kts, src/main/kotlin/one/oktw/galaxy/Main.kt, src/main/kotlin/one/oktw/galaxy/chat/Exchange.kt
=> Add chat exchange to exchange message between server

src/main/java/one/oktw/galaxy/mixin/tweak/MixinRCON_RconClient.java, src/main/resources/fabric.mod.json, src/main/resources/tweak.mixin.json
Hide from local rcon connect message
=> Hide health check message

.gitlab-ci.yml
=> Disable gradle daemon

src/main/kotlin/one/oktw/galaxy/command/commands/Join.kt, src/main/kotlin/one/oktw/galaxy/event/EventManager.kt
* Send message for galaxy loading progress
* Prevent player spam join command
* Fix event listener throw exception cause all event broken
=> Send message for galaxy loading progress

src/main/kotlin/one/oktw/galaxy/Main.kt, src/main/kotlin/one/oktw/galaxy/chat/Exchange.kt, src/main/kotlin/one/oktw/galaxy/command/commands/Join.kt, src/main/kotlin/one/oktw/galaxy/event/EventManager.kt, src/main/kotlin/one/oktw/galaxy/event/annotation/EventListener.kt, src/main/kotlin/one/oktw/galaxy/player/PlayerControl.kt
Consumer 的 `@EventListener` 是可選的，用於控制事件是否以 `sync` (cancelable) 觸發
=> Refactor event system

src/main/kotlin/one/oktw/galaxy/command/CommandRegister.kt, src/main/kotlin/one/oktw/galaxy/command/commands/Home.kt
=> /home Command

.github/workflows/workflow.yml
=> Add GitHub Actions

build.gradle.kts, src/main/java/one/oktw/galaxy/mixin/event/MixinItem_Item.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerInteractItem_NetworkHandler.java, src/main/java/one/oktw/galaxy/network/ItemFunctionAccessor.java, src/main/kotlin/one/oktw/galaxy/event/type/PlayerInteractItemEvent.kt, src/main/kotlin/one/oktw/galaxy/player/Harvest.kt, src/main/resources/galaxy.mixin.json
> Event觸發順序是
> 方塊 - 主手
> 方塊 - 副手
> 物品 - 主手
> 物品 - 副手
> 
> 然後作物在第一個 event 就被採掉了
=> Workaround harvest bugs

src/main/java/org/spongepowered/common/bridge/RealTimeTrackingBridge.java, src/main/java/org/spongepowered/common/mixin/realtime/blockentity/AbstractFurnaceBlockEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/blockentity/BrewingStandBlockEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/entity/EntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/entity/ExperienceOrbEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/entity/ItemEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/entity/LivingEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/entity/mob/CreeperEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/entity/mob/MobEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/entity/mob/ZombieVillagerEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/entity/passive/PassiveEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/entity/player/ItemCooldownManagerMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/entity/player/PlayerEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/server/MinecraftServerMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/server/network/ServerPlayNetworkHandlerMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/server/network/ServerPlayerEntityMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/server/network/ServerPlayerInteractionManagerMixin_RealTime.java, src/main/java/org/spongepowered/common/mixin/realtime/world/WorldMixin_RealTime.java, src/main/resources/fabric.mod.json, src/main/resources/sponge.realtime.mixin.json
=> Realtime patch

.github/workflows/workflow.yml
=> Actions build docker

.github/workflows/workflow.yml
Build and push docker image to OKTW Registry.
Master -> latest
~~Pull Request -> PR ID~~
Branch -> branch name
=> Add Registry to GitHub Actions

.github/workflows/workflow.yml
Add wrapper validation from https://github.com/marketplace/actions/gradle-wrapper-validation
=> Add wrapper validation

.github/workflows/workflow.yml
=> Upgrade Action cache to v2

src/main/java/one/oktw/galaxy/mixin/interfaces/CustomRecipeManager.java, src/main/java/one/oktw/galaxy/mixin/recipe/MixinCustomRecipe_CraftingResultSlot.java, src/main/java/one/oktw/galaxy/mixin/recipe/MixinCustomRecipe_PlayerManager.java, src/main/java/one/oktw/galaxy/mixin/recipe/MixinCustomRecipe_RecipeManager.java, src/main/kotlin/one/oktw/galaxy/Main.kt, src/main/kotlin/one/oktw/galaxy/recipe/tools/Wrench.kt, src/main/resources/fabric.mod.json, src/main/resources/recipe.mixin.json
`CustomRecipeManager` Allow register custom recipe.
=> Custom recipe

build.gradle.kts, src/main/java/one/oktw/galaxy/mixin/accessor/AsyncChunk_VersionedChunkStorage.java, src/main/java/one/oktw/galaxy/mixin/interfaces/AsyncChunk_StorageIoWorker.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinAsyncChunk_StorageIoWorker.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinAsyncChunk_ThreadedAnvilChunkStorage.java, src/main/resources/accessor.mixin.json, src/main/resources/fabric.mod.json, src/main/resources/galaxy-tweak.accesswidener, src/main/resources/tweak.mixin.json
Make chunk load not block ticking
=> Async chunk load

src/main/java/one/oktw/galaxy/mixin/interfaces/IThrownCountdown_Entity.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinThrownCountdown_Entity.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinThrownCountdown_ProjectileEntity.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinThrownCountdown_ThrownEntity.java, src/main/resources/tweak.mixin.json
=> Remove entity if it stuck on water

src/main/kotlin/one/oktw/galaxy/command/commands/admin/GetItem.kt
- 把一些沒有物品不應該顯示在 admin getItem 的物品移除
=> Admin getBlock cold fix

src/main/java/one/oktw/galaxy/mixin/tweak/MixinMapExistingChunk_FilledMapItem.java, src/main/resources/tweak.mixin.json
=> Map only read existing chunk

src/main/kotlin/one/oktw/galaxy/block/event/BlockEvents.kt, src/main/kotlin/one/oktw/galaxy/item/event/Wrench.kt
=> Fix wrench

src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerAction_NetworkHandler.java, src/main/kotlin/one/oktw/galaxy/Main.kt, src/main/kotlin/one/oktw/galaxy/block/event/AngelBlock.kt, src/main/kotlin/one/oktw/galaxy/block/event/BlockEvents.kt, src/main/kotlin/one/oktw/galaxy/block/type/BlockType.kt, src/main/kotlin/one/oktw/galaxy/block/util/CustomBlockUtil.kt, src/main/kotlin/one/oktw/galaxy/command/commands/admin/GetItem.kt, src/main/kotlin/one/oktw/galaxy/event/type/PlayerActionEvent.kt, src/main/resources/galaxy.mixin.json
=> AngelBlock

src/main/kotlin/one/oktw/galaxy/item/event/Wrench.kt
=> Bug fix #345

src/main/kotlin/one/oktw/galaxy/item/Tool.kt, src/main/kotlin/one/oktw/galaxy/item/Weapon.kt
- Fix styled custom item name color broken after 1.16 upgrade (#317)
=> Item Color Coldfix

src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
效能改進(希望有)、更好看的Code以及新的判定機制。
現在電梯以及下一個電梯上方一格非實心方塊 -> 允許傳送 否則 不傳送
=> Rewrite elevator.

src/main/kotlin/one/oktw/galaxy/block/event/AngelBlock.kt
=> 修正AngelBlock不能被放在CAVE_AIR上的問題。

src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerUseItemOnBlock_ItemStack.java, src/main/kotlin/one/oktw/galaxy/block/event/BlockEvents.kt, src/main/kotlin/one/oktw/galaxy/block/util/CustomBlockUtil.kt, src/main/kotlin/one/oktw/galaxy/event/type/PlayerUseItemOnBlock.kt
Allow creative mode place and break custom block
=> Refactor BlockEvents

src/main/kotlin/one/oktw/galaxy/player/Sign.kt
=> Add sign editor check

src/main/java/one/oktw/galaxy/mixin/tweak/MixinFixBeacon_BeaconBlockEntity.java, src/main/resources/tweak.mixin.json
https://bugs.mojang.com/browse/MC-153385
=> Fix MC-153385

README.md
Add [![Galaxy Actions](https://github.com/OKTW-Network/Galaxy/actions/workflows/workflow.yml/badge.svg)](https://github.com/OKTW-Network/Galaxy/actions/workflows/workflow.yml) to README.md
=> Add Github Action Badge

src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerInteractItem_NetworkHandler.java
=> Fix not cancel client use item

build.gradle.kts, src/main/java/one/oktw/galaxy/mixin/tweak/MixinAsyncChunk_ThreadedAnvilChunkStorage.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinCustomBlockEntity_Clone.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinCustomBlockEntity_Structure.java, src/main/kotlin/one/oktw/galaxy/block/entity/DummyBlockEntity.kt, src/main/kotlin/one/oktw/galaxy/block/entity/ModelCustomBlockEntity.kt, src/main/kotlin/one/oktw/galaxy/item/CustomItem.kt, src/main/kotlin/one/oktw/galaxy/item/Tool.kt, src/main/kotlin/one/oktw/galaxy/item/Weapon.kt, src/main/kotlin/one/oktw/galaxy/util/CustomRegistry.kt, src/main/resources/fabric.mod.json, src/main/resources/galaxy.accesswidener, src/main/resources/tweak.mixin.json
- Rename tag to nbt
- Fix custom item cache
- Fix clone custom block
=> Random fix

build.gradle.kts, settings.gradle.kts
=> Update library and deprecated syntax

.mergify.yml
* https://github.com/OKTW-Network/Docker-Galaxy/pull/30
* Update mergify
=> Bump docker

src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerInteractBlock_NetworkHandler.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinCustomBlockEntity_BarrierBlock.java, src/main/kotlin/one/oktw/galaxy/block/event/BlockEvents.kt, src/main/kotlin/one/oktw/galaxy/event/type/PlayerInteractBlockEvent.kt
* Fix interact lock
* Move trigger to BlockEvents
=> Fix click custom block

src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerAction_NetworkHandler.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerChat_MeCommand.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerChat_NetworkHandler.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerChat_SayCommand.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerInteractBlock_NetworkHandler.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerInteractItem_NetworkHandler.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerJump_NetworkHandler.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerSneak_NetworkHandler.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerUpdateSign_NetworkHandler.java, src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerUseItemOnBlock_ItemStack.java, src/main/kotlin/one/oktw/galaxy/event/EventManager.kt
=> EventManager add static emit function

.github/workflows/workflow.yml
https://www.docker.com/blog/image-rebase-and-improved-remote-cache-support-in-new-buildkit/
ref: https://github.com/OKTW-Network/Docker-Galaxy/pull/36
=> Docker BuildKit update

src/main/kotlin/one/oktw/galaxy/Main.kt, src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt, src/main/kotlin/one/oktw/galaxy/command/commands/Home.kt, src/main/kotlin/one/oktw/galaxy/command/commands/Spawn.kt, src/main/kotlin/one/oktw/galaxy/gui/GUI.kt
* Make InventoryEditor async
* Clean up GlobalScope
=> Improve async

src/main/java/one/oktw/galaxy/mixin/accessor/ThreadedAnvilChunkStorageAccessor.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinAsyncChunk_ChunkPosDistanceLevelPropagator.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinAsyncChunk_RegionFile.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinAsyncChunk_ServerChunkManager.java, src/main/java/one/oktw/galaxy/mixin/tweak/MixinAsyncChunk_StorageIoWorker.java, src/main/kotlin/one/oktw/galaxy/util/KotlinCoroutineTaskExecutor.kt, src/main/resources/accessor.mixin.json, src/main/resources/tweak.mixin.json
=> Reduce chunk loading memory

src/main/kotlin/one/oktw/galaxy/recipe/RecipeRegistry.kt, src/main/kotlin/one/oktw/galaxy/recipe/blocks/Trashcan.kt
=> feat: Add trashcan recipe

.gitignore, src/main/kotlin/one/oktw/galaxy/block/entity/ModelCustomBlockEntity.kt
=> Replace Armor stand to Display entity

src/main/kotlin/one/oktw/galaxy/item/Material.kt, src/main/kotlin/one/oktw/galaxy/item/Tool.kt, src/main/kotlin/one/oktw/galaxy/item/Upgrade.kt, src/main/kotlin/one/oktw/galaxy/item/Weapon.kt, src/main/resources/data/galaxy/recipe/tools/crowbar.json, src/main/resources/data/galaxy/recipe/tools/wrench.json
- replace base item of non block item to recovery compass
- Closes #442
- ~~(TBD) Gui~~
=>  refactor: replace base item of non block item to recovery compass 
